Update dice.py
SENATOROVAI/dice-rolling-simulator-team pull request #1
Opened 2023-05-20 06:04 UTC by oleg14038

Подскажите, правильно ?

2023-05-20 13:37 UTC, ruslansenatorov reviewed
вернуть забыл, и используй метод рандинт

2023-05-21 08:16 UTC, oleg14038 commented
прочитал - random.random() — возвращает псевдослучайное число,  из - за этого не написал оператор   return, теперь понял , что return возращает из функции

2023-05-21 08:24 UTC, oleg14038 commented
ар

2023-05-21 16:22 UTC, ruslansenatorov requested changes
Ок?

2023-05-21 16:24 UTC, merged