check
SENATOROVAI/dice-rolling-simulator-team pull request #2
Opened 2023-05-20 09:36 UTC by SergeyMarfin

не уверен правильно или нет!

2023-05-20 13:40 UTC, ruslansenatorov reviewed
внимательно)

2023-05-20 16:08 UTC, ruslansenatorov requested changes
убери файл dice, твой пул только один файл должен содержать

2023-05-20 16:12 UTC, SergeyMarfin commented
Это потому что я его тоже сделал)

2023-05-21 08:18 UTC, oleg14038 commented
ок

2023-05-21 08:21 UTC, oleg14038 approved these changes

2023-05-21 08:21 UTC, oleg14038 approved these changes

2023-05-21 08:33 UTC, oleg14038 approved these changes

2023-05-26 23:06 UTC, merged

2023-05-26 23:06 UTC, ruslansenatorov commented
GOOD!!!!

2023-05-26 23:14 UTC, ruslansenatorov reviewed
Ok